version: 2

builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
        - -s -w -X github.com/sniptt-official/ots/build.Version={{.Version}}

archives:
  - formats: tar.gz
    format_overrides:
      - goos: windows
        formats: zip
