name: Go CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Test, Lint, and Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./... -v
      
    - name: Lint the project
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60

    - name: Build the project
      run: go build -v main.go
